#Assignment-2

#Section A: Data Structures & Control Structures

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
my_list = [10, 20, 30, 40, 50]
my_list

In [ ]:
my_list.append(60)
my_list

In [ ]:
my_list.extend([70,80])
my_list

In [ ]:
my_list.insert(2,90) ##1st one for index position to insert and next for value
my_list

In [ ]:
my_list.remove(30)
my_list

In [ ]:
Pop=my_list.pop()
Pop

In [ ]:
Index=my_list.index(40)
Index

In [ ]:
my_list.append(40)
c=my_list.count(40)
c

In [ ]:
my_list.sort()
my_list

In [ ]:
my_list.reverse()
my_list

In [ ]:
student_tuple = ("Alice", "Bob", "Charlie")
student_tuple

In [ ]:
 student_tuple[1] = "David"

 'tuple' is an immutable object

In [47]:
my_set = {1, 2, 3, 2, 4, 5, 3, 6, 1}
my_set
##Sets automatically remove duplicate values and store

{1, 2, 3, 4, 5, 6}

In [48]:
person_dict = {'name': 'John Doe', 'age': 25, 'city': 'New York'}
person_dict

{'name': 'John Doe', 'age': 25, 'city': 'New York'}

In [50]:
person_dict['age'] = 26
person_dict['email']='john.c.breckinridge@altostrat.com'
person_dict

{'name': 'John Doe',
 'age': 26,
 'city': 'New York',
 'email': 'john.c.breckinridge@altostrat.com'}

In [51]:
a=int(input("Enter your age= "))

if a>= 18:
    print("Congrats")
    print("Your eligible to vote")
else:
    print("Sorry better luck next time")
    print("Not eligible")

print("Bye")

Enter your age= 13
Sorry better luck next time
Not eligible
Bye

In [52]:
marks=int(input())

if marks>=0 and marks<100:
    if marks >=90:
        status="First class"
        grade="A"
    elif marks >= 75:
        status="Second class"
        grade="B"
    elif marks>=55:
        status="Third class"
        grade="C"
    elif marks>=36:
        status="Pass"
        grade="D"
    else:
        status="Fail"
        grade="F"
    print(marks)
    print(grade)
    print(status)
else:
    print("Please enter valid number")

78
78
B
Second class

In [58]:
num=int(input())
if num > 0 :
  print("Positive")
  if num % 2==0:
    print('Even')
  else:
      print("Odd")
elif num==0:
  print("Zero")
else:
  print("Negative")

-9
Negative

#Section B: Numpy

In [62]:
scalar = np.array(5)
scalar

array(5)

In [59]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [61]:
array2=np.array([[10,20,30],[40,50,60]])
array2

array([[10, 20, 30],
       [40, 50, 60]])

In [63]:
random_array=np.random.randint(0,100,size=(4,4))
random_array

array([[ 7, 88, 13, 86],
       [64, 12, 16, 96],
       [ 4, 41, 42, 33],
       [70, 76,  8, 29]])

In [66]:
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_array
df= pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

#Section C: Pandas

In [68]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 28, 32, 29, 27, 31, 26, 33],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'New York'],
    'Salary': [50000, 60000, np.nan, 55000, 62000,
               58000, np.nan, 65000, 52000, 70000]
}

df = pd.DataFrame(data)
df

      Name  Age          City   Salary
0    Alice   25      New York  50000.0
1      Bob   30   Los Angeles  60000.0
2  Charlie   35       Chicago      NaN
3    David   28       Houston  55000.0
4      Eve   32       Phoenix  62000.0
5    Frank   29  Philadelphia  58000.0
6    Grace   27   San Antonio      NaN
7    Henry   31     San Diego  65000.0
8      Ivy   26        Dallas  52000.0
9     Jack   33      New York  70000.0

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [70]:
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   29.600000  59000.000000
std     3.204164   6697.547526
min    25.000000  50000.000000
25%    27.250000  54250.000000
50%    29.500000  59000.000000
75%    31.750000  62750.000000
max    35.000000  70000.000000

In [72]:
cl=df[["Name","Age"]]
cl

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eve   32
5    Frank   29
6    Grace   27
7    Henry   31
8      Ivy   26
9     Jack   33

In [75]:
dr_drop=df.drop("City",axis=1)
dr_drop

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35      NaN
3    David   28  55000.0
4      Eve   32  62000.0
5    Frank   29  58000.0
6    Grace   27      NaN
7    Henry   31  65000.0
8      Ivy   26  52000.0
9     Jack   33  70000.0

In [78]:
salary_mean = dr_drop['Salary'].mean()
salary_mean
df_filled = dr_drop.copy()
df_filled['Salary'].fillna(salary_mean, inplace=True)
df_filled

/tmp/ipython-input-1130310556.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filled['Salary'].fillna(salary_mean, inplace=True)

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  59000.0
3    David   28  55000.0
4      Eve   32  62000.0
5    Frank   29  58000.0
6    Grace   27  59000.0
7    Henry   31  65000.0
8      Ivy   26  52000.0
9     Jack   33  70000.0

In [79]:
df_with_dup = df_filled.copy()
df_with_dup = pd.concat([df_with_dup, df_with_dup.iloc[[0]]], ignore_index=True)
print(df_with_dup)
df_no_dup = df_with_dup.drop_duplicates()
print(df_no_dup)

       Name  Age   Salary
0     Alice   25  50000.0
1       Bob   30  60000.0
2   Charlie   35  59000.0
3     David   28  55000.0
4       Eve   32  62000.0
5     Frank   29  58000.0
6     Grace   27  59000.0
7     Henry   31  65000.0
8       Ivy   26  52000.0
9      Jack   33  70000.0
10    Alice   25  50000.0
      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  59000.0
3    David   28  55000.0
4      Eve   32  62000.0
5    Frank   29  58000.0
6    Grace   27  59000.0
7    Henry   31  65000.0
8      Ivy   26  52000.0
9     Jack   33  70000.0